name: Generate Snake Animation

# O fluxo é executado a cada 12 horas ou manualmente por 'workflow_dispatch' ou ao fazer push na branch 'master'.
on:
  schedule: # Executa a cada 12 horas
    - cron: "0 */12 * * *"

  workflow_dispatch: # Permite execução manual pelo GitHub UI

  push: # Executa também ao fazer push na branch 'master'
    branches:
      - master

jobs:
  generate-snake:
    permissions:
      contents: write # Necessário para fazer push do arquivo gerado
    runs-on: ubuntu-latest # Usa a última versão do Ubuntu
    timeout-minutes: 5

    steps:
      # Passo para gerar o arquivo snake.svg
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ArthurFreddo # Seu nome de usuário do GitHub
          outputs: dist/snake.svg?palette=github-dark # Define a paleta de cores como "github-dark"

      # Passo para fazer push do snake.svg gerado para o branch de saída
      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output # Nome do branch de destino (você pode mudar para o branch de sua escolha)
          build_dir: dist # Diretório onde o snake.svg é gerado
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Usa o token do GitHub para fazer o push
